### ISSUE TITLE
"GIS Data Handling" & "Animal Detection ...." tool sections on the "PROTEOMICS, METABOLOMICS, CHEMISTRY" tool "supersection" instead of "MISCELLANEOUS TOOLS" or other

### ISSUE THREAD

**Issue by yvanlebras** [usegalaxy-eu/infrastructure-playbook#107]
Hi usegalaxy.eu team !

Just see that "GIS Data Handling" & "Animal Detection on Acoustic Recordings" tool sections are localized on the "PROTEOMICS, METABOLOMICS, CHEMISTRY" tool "supersection" instead of "MISCELLANEOUS TOOLS" or other.

Cheers,

Yvan

**Comment by bgruening** [comment]
Hopefully https://github.com/usegalaxy-eu/infrastructure-playbook/commit/56d2200d8e380fd8e8e87bfb0d2b9900bdc1ff93 fixes that.
