### ISSUE TITLE
Runtime dependency issue recetox_msfinder v3.5.2+galaxy4

### ISSUE THREAD

**Issue by jennaj** [usegalaxy-eu/infrastructure-playbook#1092]
toolshed.g2.bx.psu.edu/repos/recetox/recetox_msfinder/recetox_msfinder/v3.5.2+galaxy4

> /data/jwd05e/main/066/778/66778816/tool_script.sh: line 9: mono: command not found rm: cannot remove 'output/result.msp': No such file or directory

Test history using tool test data: https://usegalaxy.eu/u/jenj/h/test-recetox-msfinder

Reported at https://help.galaxyproject.org/t/recetox-msfinder-not-working-on-usegalaxy-eu/11612/2

**Comment by bgruening** [comment]
This is a Docker tool. I have added it to TPV like that:

https://github.com/usegalaxy-eu/infrastructure-playbook/commit/6cd91e4e845e713b4a4187b12170bbbe6ac37d35

I hope this is working now.

**Comment by hechth** [comment]
@bgruening I'll check :)

**Comment by hechth** [comment]
Still not working, but for a different reason - maybe we have to update the wrapper script a bit, I will try to make it a bit simpler.

**Comment by hechth** [comment]
Still the same - `mono: command not found` and then `rm: command not found`

**Comment by hechth** [comment]
@bgruening and @mira-miracoli this is still not working - were there any changes to how the tool is run?

**Comment by hechth** [comment]
@bgruening @jennaj @mira-miracoli ping

**Comment by sanjaysrikakulam** [comment]
I have tested it with the `test.msp` input file available in the history shared above, and my job finished successfully using the default values defined for the tool.

@hechth Please rerun your job and let us know whether it's working now.

**Comment by hechth** [comment]
@sanjaysrikakulam yes, this was fixed - thanks a lot @bgruening and @jennaj
