### ISSUE TITLE
restart workflow-scheduler processes after deployment

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#110]
The new workflow-scheduler processes will not be restarted currently. I found a few processes running more then a month now :)

**Comment by erasche** [comment]
yikes, should add to the auto-restart cron job too.

**Comment by bgruening** [comment]
We do have a auto-restart cron? Why?

**Comment by bgruening** [comment]
Ok, then we need to fix the cron as well.

**Comment by bgruening** [comment]
Should     job: systemctl restart galaxy-handler@6 galaxy-handler@7 galaxy-handler@8 galaxy-handler@9 galaxy-handler@10 galaxy-handler@11

**Comment by erasche** [comment]
Ugh that's what's been restaarting those.
