### ISSUE TITLE
clenaup directories

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#120]
It seems:

* /data/7/galaxy_db/tmp/
* /data/dnb01/galaxy_db/pbs 

is not cleaned up, or we should cleanup more often.

**Comment by gmauro** [comment]
fixed by https://github.com/usegalaxy-eu/infrastructure-playbook/tree/master/roles/usegalaxy-eu.fs-maintenance

**Comment by bgruening** [comment]
The PBS dirs can probably be removed by now.

**Comment by gmauro** [comment]
> The PBS dirs can probably be removed by now.

is empty

**Comment by bgruening** [comment]
Jupp, do we can remove the dir and the cleanup job?
