### ISSUE TITLE
Single cell subdomain on .eu

### ISSUE THREAD

**Issue by nomadscientist** [usegalaxy-eu/infrastructure-playbook#1333]
Can the single-cell subdomain page now render from our new Lab page (https://labs.usegalaxy.org.au/?content_root=https://github.com/galaxyproject/galaxy_codex/blob/main/communities/spoc/lab/usegalaxy.eu.yml) please?

Additionally, could our tool panel be organised using that curated list (https://github.com/galaxyproject/galaxy_codex/tree/main/communities/spoc/lab/tool_panel)?

**Comment by mira-miracoli** [comment]
I opened the above PR for your iframe/welcome page
Unfortunately, Codex is not supported in usegalaxy.eu yet.

**Comment by bgruening** [comment]
@mira-miracoli feel free to merge.

@nomadscientist I'm not sure this is a good idea in general. We are now loading a website from the other side of the world. There might be some slowdowns. Look out for that.

**Comment by nomadscientist** [comment]
@neoformit Björn raised an interesting point - thoughts on this?

**Comment by neoformit** [comment]
I did look at the latency from AU to US and I think it seemed like 200ms. If it's problematic, we could easily deploy a labs-engine in europe, it's all Ansiblized.

**Comment by neoformit** [comment]
@bgruening we compared a latency test from Brisbane (me) and Wendi (London) and there was only 50ms difference. Is that helpful, or could the latency still be higher with different time/location?

**Comment by bgruening** [comment]
If @nomadscientist and the single-cell community is happy, I am as well.

For African researchers, we stripped / created a specific landing page to reduce the load at some point.

**Comment by nomadscientist** [comment]
That's a really good and interesting point.  What number / target / metric do we need to aim for for enabling people with poorer WiFi connections to access?
