### ISSUE TITLE
Single-cell central subdomain

### ISSUE THREAD

**Issue by nomadscientist** [usegalaxy-eu/infrastructure-playbook#1343]
I know that https://github.com/usegalaxy-eu/infrastructure-playbook/pull/1334 meant that the single-cell page should pull from the CoDex, however, it's still showing the 'old' home page.

Any ideas why?

**Comment by mira-miracoli** [comment]
Because I was a little bit unattentive and gave it the wrong filename.
Should be `index.html`
I will open a pr to fix this

**Comment by nomadscientist** [comment]
Oh this is awesome news, it's so nice when it's simple! 
Thank you so much!

**Comment by mira-miracoli** [comment]
Wasn't that easy.. I guess I need to have a closer look

**Comment by mira-miracoli** [comment]
There is a mistake in the subdomain ansible role version that we are running, I need to look into this in a quiet moment

**Comment by mira-miracoli** [comment]
https://github.com/galaxyproject/ansible-galaxy/issues/220

**Comment by mira-miracoli** [comment]
https://github.com/galaxyproject/ansible-galaxy/pull/221
should fix it

**Comment by mira-miracoli** [comment]
fixed by https://github.com/galaxyproject/ansible-galaxy/pull/221
