### ISSUE TITLE
sync.sh is not part of the playbook

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#209]
This script is used to sync local storage to network storage. Its in HOME.

**Comment by gmauro** [comment]
No, don't rely on that. Use /usr/bin/galaxy-sync-to-nfs instead

**Comment by bgruening** [comment]
@gmauro ok. Can you please remove the old one then, document the new one and make sure it is called on cron and after tool installation. Thanks.

**Comment by gmauro** [comment]
Added a [note](https://github.com/usegalaxy-eu/operations/blob/master/storage.md) of the current situation

**Comment by bgruening** [comment]
Thanks!

**Comment by gmauro** [comment]
Now we have this Jenkins chain:
Upstream Projects
  usegalaxy-eu » update-trusted-tools

Central Projects
  usegalaxy-eu » install-tools

Downstream Projects
  usegalaxy-eu » playbooks » sync_to_nfs

https://build.galaxyproject.eu/job/usegalaxy-eu/job/install-tools/

This means that will be built update-trusted-tools as first, then install-tools and then sync_to_nfs

**Comment by gmauro** [comment]
updated the [note](https://github.com/usegalaxy-eu/operations/blob/master/storage.md)

**Comment by bgruening** [comment]
Cool!
