### ISSUE TITLE
Give all ELIXIR AAI users 500 GB

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#212]
`select user_id from oidc_user_authnz_tokens where provider = 'elixir';` is providing us with a list of all ELIXIR users.

There is actually now a nice site now https://usegalaxy.eu/user/external_ids where a user is able to jump in and out.

Could we take this and increase the quota to 500 if user_id is included in the query?

A simple cron would work?

**Comment by bgruening** [comment]
ping @hexylena @gmauro

**Comment by hexylena** [comment]
Yeah. Cron sounds like the easiest solution here, please add it to gxadmin :)

**Comment by bgruening** [comment]
How do you envision such a gxadmin command?

`gxadmin mutate set_quota_for_oidc_user --provider 'elixir' --quota 500`  ??

**Comment by hexylena** [comment]
Yeah, but maybe '--quota elixir' to detach quota creation (ugly, painful) with attaching the user to that quota.

**Comment by bgruening** [comment]
So manually creating an ELIXIR quota and adding users to this one. Like this idea.

**Comment by bgruening** [comment]
Ok, there is now a quota `ELIXIR`.

**Comment by hexylena** [comment]
you could probably do something like

```
begin transaction;
delete from user_quota_association where quota_id=19;
with t as (select user_id, 19, now(), now() from oidc_user_authnz_tokens where provider = 'elixir') insert into user_quota_association (user_id, quota_id, create_time, update_time) select * from t;
commit;
```

really unfortunate that no one ever put unique constraints on that table or this would be significantly easier to do lol.
