### ISSUE TITLE
change support_url

### ISSUE THREAD

**Issue by OlegZharkov** [usegalaxy-eu/infrastructure-playbook#216]
Not sure if it's the correct repo for this issue, please lead me to another if it's not. 

As discussed today during the code day, if you open `Help` dropdown on https://usegalaxy.eu/ `Galaxy help` and `Support` opens the same page.

We probably want to make `Support` open `https://galaxyproject.org/support/`.

To do that, we need to change `support_url` value in `galaxy.yml`

**Comment by bgruening** [comment]
@OlegZharkov you can change this in the galaxy.yml file, see here https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L892

In this repo here: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/group_vars/gxconfig.yml#L595

**Comment by OlegZharkov** [comment]
> @OlegZharkov you can change this in the galaxy.yml file, see here https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L892
> 
> In this repo here: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/group_vars/gxconfig.yml#L595

it's already `https://galaxyproject.org/support/`. But on usegalaxy.eu it's clearly `https://help.galaxyproject.org/c/usegalaxy-eu-support/`. Are you sure, that it's correct repo? maybe it's not the latest version deployed

**Comment by gmauro** [comment]
that's the correct variable
https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0113536f88e140337389ae505fc85f0adb5eb8c5/group_vars/gxconfig.yml#L764
but IMHO should be:
Galaxy Help > https://galaxyproject.org/support/
Support > https://help.galaxyproject.org/c/usegalaxy-eu-support/

**Comment by OlegZharkov** [comment]
> but IMHO should be:
> Galaxy Help > https://galaxyproject.org/support/
> Support > https://help.galaxyproject.org/c/usegalaxy-eu-support/

Why? on org they have

Galaxy Help > forum-like website https://help.galaxyproject.org/ 
Support > https://galaxyproject.org/support/

So on EU, I suppose it should be
Galaxy Help > https://help.galaxyproject.org/c/usegalaxy-eu-support/ (EU part of that forum)
Support > https://galaxyproject.org/support/

Is it good enough?

**Comment by gmauro** [comment]
Seems confusing to me. "Galaxy Help" suggest to me a general help on Galaxy, "support", instead, a Usegalaxy.eu specific link.

**Comment by OlegZharkov** [comment]
Isn't it a bit unintuitive, that help button will go to support (https://galaxyproject.org/support/) and support to help (https://help.galaxyproject.org/)?

Also, we maybe want kind of consistency with org

**Comment by beatrizserrano** [comment]
> Galaxy Help > https://help.galaxyproject.org/c/usegalaxy-eu-support/ (EU part of that forum)
> Support > https://galaxyproject.org/support/

That is what I think that we agreed last Friday, so I guess that the only change to make is to replace the next URL by  https://galaxyproject.org/support/

> https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0113536f88e140337389ae505fc85f0adb5eb8c5/group_vars/gxconfig.yml#L764

**Comment by OlegZharkov** [comment]
> > Galaxy Help > https://help.galaxyproject.org/c/usegalaxy-eu-support/ (EU part of that forum)
> > Support > https://galaxyproject.org/support/
> 
> That is what I think that we agreed last Friday, so I guess that the only change to make is to replace the next URL by https://galaxyproject.org/support/
> 
> > https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0113536f88e140337389ae505fc85f0adb5eb8c5/group_vars/gxconfig.yml#L764

Ok, here we go https://github.com/usegalaxy-eu/infrastructure-playbook/pull/219
