### ISSUE TITLE
telegraf should be in the systemd-journal group

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#253]
This is from sn06: `systemd-journal:x:190:gxpriv,telegraf,galaxy`

**Comment by bgruening** [comment]
Not sure what gxpriv is or was. @hexylena?

**Comment by hexylena** [comment]
Earlier i tried using the full priv sep setup, which involved a second non root user responsible for managing gx configs. Deleted it later, unnecessary complexity

**Comment by gmauro** [comment]
fe6cbda99907ac82a8934324566cd621e2c32d9b close #253
