### ISSUE TITLE
file sources conf

### ISSUE THREAD

**Issue by hexylena** [usegalaxy-eu/infrastructure-playbook#278]
Could this be decrypted again? If it's moved to the templates directory, I'm sure any passwords in there could be moved to the vault. I found this file to be a great reference for myself (since it's more extensive than galaxy's documentation) and I'm sure for other admins too.

**Comment by gmauro** [comment]
I try to find time to fix it

**Comment by bgruening** [comment]
See also here: https://github.com/galaxyproject/galaxy/pull/11949
