### ISSUE TITLE
pulsar network nodes: default container expects cvmfs present

### ISSUE THREAD

**Issue by martenson** [usegalaxy-eu/infrastructure-playbook#312]
Can be seen here: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/dynamic_rules/usegalaxy/destination_specifications.yaml#L678

Is this image hosted somewhere reachable without cvmfs?

**Comment by bgruening** [comment]
You can download this container and stick is somewhere.

**Comment by martenson** [comment]
I understand that, I was think more of a switching the default since having cvmfs available does not need to be a requirement for the pulsar network for now.

**Comment by bgruening** [comment]
But you can change that path for your destiation, correct?

**Comment by martenson** [comment]
I believe so, through the linked file.

**Comment by martenson** [comment]
I guess there really is no "default" per say. I'll close this, thanks for clarifying.
