### ISSUE TITLE
Increase cores on Maker

### ISSUE THREAD

**Issue by jaredbernard** [usegalaxy-eu/infrastructure-playbook#314]
Hi there,
The default number of cores for Maker appears to be 1. Is there a way for me to increase the number of cores so the jobs execute faster? My current Maker jobs have been running for 2 weeks (and still going), and I know of someone else whose job ran for 3 weeks. I have several rounds of Maker yet to do, so this is a long time for each round. I understand that fewer cores are allotted to increase availability to more Galaxy users, but executing jobs faster would also free up space for more users.

If this is too much trouble, please disregard this request. But if possible I would prefer the number of cores to be > 4 (the number my laptop has); somewhere between 5 and 8 cores would be great.

Sorry if I'm leaving this issue in an unusual place, but I didn't see an appropriate alternative.

**Comment by bgruening** [comment]
@jaredbernard indeed you can do this by manipulating this file https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/dynamic_rules/usegalaxy/tool_destinations.yaml 

You need to know the tool ID. I can do this as soon as I'm back from vacation. Please feel free to give it 12 cores if you feel like modifying this file.

**Comment by jaredbernard** [comment]
Thanks!

**Comment by bgruening** [comment]
Added maker with 12 cores. It will be available from tm onwards.
