### ISSUE TITLE
special destinations are overwritten by training groups

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#45]
The 'condor_docker' is essential for a few tools and if it gets overwritten it does not work. I don't think we have this logic currently in our setup.

What happened is that people in a training group, no matter if this training was currently running or long time ago was not routed to the 'condor_docker' destination but ended up in 'condor', where the tool crashed.

**Comment by erasche** [comment]
Ok, found the wrong line. Yeah, makes sense.

**Comment by bgruening** [comment]
https://usegalaxy.eu/u/bgruening/h/copy-of-testing-msconvert

If you need a test, this tool run fine if you are not in any training group and crashes if you are ....

**Comment by erasche** [comment]
Thanks!

**Comment by erasche** [comment]
Should be fixed
