### ISSUE TITLE
beautifulsoup bs4 is missing in venv

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#46]
needed for phd commics

**Comment by erasche** [comment]
the venv installation task was uncommented for a while, while we fixed our zerg mess. https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/galaxy.yml#L67 it is enabled since a few days and next time I run the playbook it'll be corrected.

**Comment by erasche** [comment]
Fixed
