### ISSUE TITLE
add tmpwatch to cron

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#61]
```bash
tmpwatch 30d /data/dnb01/galaxy_db/tmp/
```

and probably all other /data/*/galaxy_db/tmp/ dirs should clean up TB of data.

yum install tmpwatch needs to be also added.
I just removed a few TBs over the weekend.

**Comment by erasche** [comment]
I have been cleaning them with `gxadmin galaxy cleanup-jwd` which checks job states before deleting the files which should hopefully be quite safe. I've removed a couple of the old JWDs already, and am continuing to make progress with this method. I prefer it slightly to tmpwatch, and I'll add it to cron soon

**Comment by bgruening** [comment]
Just to be sure, this is not about JWDs, it's about .../tmp. This wasn't cleaned for 2 years, afaict.

**Comment by erasche** [comment]
Oh, I misread. Yeah, ok.
