### ISSUE TITLE
interproscan installation log

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#67]
1. download (current interproscan-5.36-75.0-64-bit.tar.gz) Interproscan to /data/0/interproscan
2. unpack
3. add `-Duser.home=/data/2/galaxy_db/tmp` to interproscan.properties at the end, the path does not seem to be relevant
4. install Phobius, TMHMM, SignalP_EUK, and Panther manually in the locations given in interproscan.properties
5. change the path in https://github.com/usegalaxy-eu/infrastructure-playbook/commit/41de094887cf0dc151efe2062b64db54a5a8a690 if necessary

**Comment by erasche** [comment]
Ok, we should write a role for this. I'll add to my list.

**Comment by erasche** [comment]
> install Phobius, TMHMM, SignalP_EUK, and Panther manually

those all require like sending an email don't they? :sob:

**Comment by bgruening** [comment]
Not all, 2 I think, a few we already have locally and they never change and I just reused them.
