### ISSUE TITLE
Add more RAM to HyPo for ERGA ONT-based assembly

### ISSUE THREAD

**Issue by diegomics** [usegalaxy-eu/infrastructure-playbook#692]
@gallardoalba 
HyPo (toolshed.g2.bx.psu.edu/repos/iuc/hypo/hypo/1.0.3+galaxy0) is failing, likely because of a RAM issue.

```
cgroup
CPU Time	1 hour and 55 minutes
Failed to allocate memory count	20214531.0000000
Memory limit on cgroup (MEM)	36.0 GB
Max memory usage (MEM)	36.0 GB
Memory limit on cgroup (MEM+SWP)	8.0 EB
Max memory usage (MEM+SWP)	36.0 GB
OOM Control enabled	No
Was OOM Killer active?	No
Memory softlimit on cgroup	0 bytes

core
Cores Allocated	8
Memory Allocated (MB)	4096
Job Start Time	2023-04-28 10:30:08
Job End Time	2023-04-28 11:30:17
Job Runtime (Wall Clock)	1 hour and 0 minutes
```

**Comment by bgruening** [comment]
If you like you can change this line here :)

https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/dynamic_rules/usegalaxy/tool_destinations.yaml#L924

**Comment by mira-miracoli** [comment]
I created a PR for this:
https://github.com/galaxyproject/tpv-shared-database/pull/20
