### ISSUE TITLE
repeat_masker: set different values for environment variables for different ranges of tool versions

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/infrastructure-playbook#700]
Follow up at https://github.com/usegalaxy-eu/infrastructure-playbook/pull/699

**Comment by bgruening** [comment]
https://github.com/usegalaxy-eu/infrastructure-playbook/pull/699#issuecomment-1534448013

**Comment by kysrpex** [comment]
Solved using the [helper functions to compare tool versions](https://github.com/usegalaxy-eu/infrastructure-playbook/pull/699#issuecomment-1534448013) in #728.
