### ISSUE TITLE
Error reading toolshed.g2.bx.psu.edu/repos/devteam/concat/855580142a12/concat/concat.xml

### ISSUE THREAD

**Issue by kysrpex** [usegalaxy-eu/infrastructure-playbook#886]
```
Error reading tool configuration file from path 'toolshed.g2.bx.psu.edu/repos/devteam/concat/855580142a12/concat/concat.xml': FileNotFoundError(2, 'No such file or directory')
```
Source: [Sentry](https://sentry.galaxyproject.org/organizations/galaxy/issues/124159/events/1f9636a4438c4ecd9eb65c9c48f873fb/)

Somebody disabled the tool renaming concat.xml to concat._xml. Revision 32e1c8dac438 is at the moment also installed, tagged with the same version number and working. I thus suggest to remove the tool from migrated_tools_conf.xml (the configuration pointing to the xml file) and remove the directory /opt/galaxy/shed_tools-local/toolshed.g2.bx.psu.edu/repos/devteam/concat/855580142a12 (or use the GUI to uninstall this revision).

**Comment by bgruening** [comment]
Can you comment the tool out in the migration yaml? You can remove the sir from the harddrive.

**Comment by kysrpex** [comment]
> Can you comment the tool out in the migration yaml? You can remove the sir from the harddrive.

Done, the PR to approve is #887.
