### ISSUE TITLE
usegalaxy-eu.htcondor_release: first job resubmission does not increase `request_memory`

### ISSUE THREAD

**Issue by kysrpex** [usegalaxy-eu/infrastructure-playbook#896]
```
  06/09/2023-18:15:02, rerunning held job, id *******1, description freebayes, memory_provisioned 9472, request_memory 28416, vgcnbwc-worker-c120m425-0003
  06/09/2023-18:15:02, rerunning held job, id *******1, description freebayes, memory_provisioned 9472, request_memory 28416, vgcnbwc-worker-c120m425-0003
  06/09/2023-19:00:01, rerunning held job, id *******1, description freebayes, memory_provisioned 28416, request_memory 85248, vgcnbwc-worker-c120m425-7602
  07/09/2023-14:00:01, rerunning held job, id *******6, description freebayes, memory_provisioned 9472, request_memory 28416, vgcnbwc-worker-c36m100-0000
  07/09/2023-14:00:06, rerunning held job, id *******6, description freebayes, memory_provisioned 9472, request_memory 28416, vgcnbwc-worker-c36m100-0000
  07/09/2023-14:15:02, rerunning held job, id *******6, description freebayes, memory_provisioned 28416, request_memory 85248, vgcnbwc-worker-c120m425-0008
```

Jobs are resubmitted up to three times when they run out of memory, but the first resubmission has no effect, so #881 is leaving out more jobs than we expected.

**Comment by kysrpex** [comment]
@sanjaysrikakulam What do you think of this?

Adding some echo statements shows that condor_qedit requests the correct amount of memory. Maybe condor_release is called too fast after condor_qedit? Should we try adding `sleep 1` or `sleep 0.5` [in between these two lines](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/1202d2fefb3d76dc071dba45df37dabfa18d45d6/roles/usegalaxy-eu.htcondor_release/tasks/main.yml#L37-L38) and watch how it behaves?

**Comment by sanjaysrikakulam** [comment]
You can try with `sleep 0.5,` but I doubt whether this could be a reason.

**Comment by kysrpex** [comment]
> You can try with `sleep 0.5,` but I doubt whether this could be a reason.

That suggestion is from last Friday before I realized logs were being written twice... We have already discussed in person that the problem is that the same script was running twice.

**Comment by kysrpex** [comment]
The stop ITs script and HTCondor release scripts as well as their crontab entries have been removed from the maintenance node. The maintenance playbook does not recreate them, and logs are being written just once now. The issue can be closed.
